CREATE DATABASE dasan_resort;
use dasan_resort;

CREATE TABLE `CARD KEY`(
  `KEY_ID` INT NOT NULL AUTO_INCREMENT COMMENT '키 ID',
  `Room_ID` INT NOT NULL COMMENT '방 ID',
  `Cust_ID` INT NOT NULL COMMENT '고객 ID',
  PRIMARY KEY (`Key_ID`));
  
ALTER TABLE `CARD KEY` COMMENT = '카드키 정보 테이블';

CREATE TABLE `SERVICE REQUIREMENT`(
`SerReq_ID` INT NOT NULL AUTO_INCREMENT COMMENT '서비스 요구 ID',
`Service_ID` INT NOT NULL COMMENT '서비스 ID',
`SerReq_Count` INT NOT NULL COMMENT '서비스 요구 횟수',
`SerReq_TotalAmount` INT NOT NULL COMMENT '서비스 총 금액',
`KEY_ID` INT NOT NULL COMMENT '키 ID',
`Cust_ID` INT NOT NULL COMMENT '고객 ID',
PRIMARY KEY (`SerReq_ID`));

ALTER TABLE `SERVICE REQUIREMENT` COMMENT = '서비스 요구 테이블';

CREATE TABLE `ROOM STATE` (
`Room_ID` INT NOT NULL AUTO_INCREMENT COMMENT '객실 ID',
`RoomState_State` BOOL NULL COMMENT '객실 사용 가능 여부',
`Cust_ID` INT NOT NULL COMMENT '고객 ID',
`Booking_ID` INT NOT NULL COMMENT '예약 ID',
`Service_ID` INT NOT NULL COMMENT '서비스 ID',
PRIMARY KEY (`Room_ID`));

ALTER TABLE `ROOM STATE` COMMENT = '객실 상태 테이블';
